### ISSUE TITLE
Make necessary preparations for a first release

### ISSUE THREAD

**Issue by markhakansson** [rpa-tomorrow/rpa-tomorrow#181]
# Summary
It would be nice to have an actual release after wrapping up this project. The release would be similar to a "binary" (not really applicable to Python) installation. Where someone can simply install the application from a tarball with all necessary dependencies bundled and no setup required. 

Before creating a release we should make the necessary preparations for it. This includes but not limited to:
* Make it possible to install the application and run both the CLI or GUI
    * E.g. `rpa-cli` or `rpa-gui` in the terminal 
* Easy to setup for the user (no extra configuration)
* All dependencies should be bundled in the release

# Examples
Some examples and docs for creating a package/distribution here:
https://docs.python.org/3/distutils/builtdist.html
https://medium.com/@amimahloof/how-to-package-a-python-project-with-all-of-its-dependencies-for-offline-install-7eb240b27418

# Context
If you have more suggestions, please add a comment or update the summary!

**Comment by Aleman778** [comment]
There should be a way to compile the GUI application to an executable using fbs, however I didn't get that to work.
